version: '3.1'
services:
    express-app:
        build: .
        ports:
            - "3000:3000"
        container_name: express_app_cont
    mongo:
        image: mongo
        container_name: mongo_cont
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
    mongo-express:
        # Default credentials for mongo express
        # username: admin
        # password: pass
        image: mongo-express
        container_name: mongo_express_cont
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
